### ISSUE TITLE
Jumper T-Lite - Not able to enter configuration mode.

### ISSUE THREAD

**Issue by Kikerumbo** [iNavFlight/OpenTX-Telemetry-Widget#103]
Greetings,

I've been trying to configure the alarms (I use Li-Ion and the alarms are set too high) and It's not possible to enter the configuration with a Jumper T-Lite with EdgeTX.

In the guide is stated that you should long press the "MENU" button to enter, but none of the buttons on the radio get me into the configuration menu of the LUA.

Can this issue be solved or can I configure the alarms in the LUA any other way?

Thanks.

**Comment by stronnag** [comment]
Works fine in the Simulator. Long press on the lower right button (whatever that may be).

![image](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/158229/dd86cfe7-86f4-4ee8-a66f-8175a97f5acc)

**Comment by Kikerumbo** [comment]
> Works fine in the Simulator. Long press on the lower right button (whatever that may be).
> 
> ![image](https://user-images.githubusercontent.com/158229/256025323-dd86cfe7-86f4-4ee8-a66f-8175a97f5acc.png)

Thanks for the answer.

The problem is still the same. Here I link a video of the issue (trying what you told me, even if I already tried before I posted). Lower right button is "MDL".

https://youtube.com/shorts/nW9xRd1KelA?feature=share

**Comment by stronnag** [comment]
Whatever, the code uses the firmware's `EVT_VIRTUAL_MENU_LONG` for the menu. If this is different in the simulator and the hardware, then it is a EdgeTX or vendor issue. Please contact them for help. The maintainer does not have access the hardware.

**Comment by stronnag** [comment]
See also #106

**Comment by Kikerumbo** [comment]
I did what I could to help, showing the issue. As I see the information isn't useful to solve a problem that does only exists with my radio, I apologize.

Since it seems I have to be "a programmer" to test why a LUA script doesn't work (I don't understand the mwptools installation guide), I'll just use the other script (GPSx9L).

Thanks for the "help".

You can re-close the issue.

**Comment by caiuspetronius** [comment]
The same problem with Commando 8.

**Comment by caiuspetronius** [comment]
Looks intriguing. And how exactly did you achieve the configuration menu on Commando 8? It took me an hour of experimenting to figure out that a long left push on the left joystick switches the screens view ).

**Comment by caiuspetronius** [comment]
I just edited the confit.lua script by hand for now.

**Comment by stronnag** [comment]
I followed the [documentation](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/blob/master/docs/Configuration-Settings.md),  maybe you should try it.

**Comment by caiuspetronius** [comment]
The link you provided has a newer version of the docs than what I was reading. There was nothing there about the new script to test buttons. Anyway, the script shows that long MDL (long right on the left joystick)sends the EVT_VIRTUAL_MENU_LONG event, but it doesn’t work for me nevertheless. I’m trying it from the screen where the iNav telemetry script is displaying its graphics. Is this the right location?
