### ISSUE TITLE
Settings On iFlight Commando8

### ISSUE THREAD

**Issue by Cloudfan-official** [iNavFlight/OpenTX-Telemetry-Widget#109]
How to enter the settings page on iFlight Commando 8?

Long press of the menu button seems to have no response.

Use Telemetry Lua V2.2.1 and EdgeTX 2.8.0.

**Comment by stronnag** [comment]
Not a supported radio:

* See [the documentation](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/blob/master/docs/Configuration-Settings.md#other-radios)
* Ask you vendor which key press provides the required virtual key
* Try the latest script from `master` which may (or not) help
* Works in the Companion/Simulator
