### ISSUE TITLE
2.2.1 breaks Crossfire Compatibility on X9D+ Radios

### ISSUE THREAD

**Issue by b14ckyy** [iNavFlight/OpenTX-Telemetry-Widget#113]
### Describe the bug
With the Version 2.2.1 on the X9D+ Radio and Crossfire the Widget shows lost telemetry alarm constantl. It still Updates certain values like Battery Voltage, Current Draw, Sat count and maybe some more but not the Attitude, GPS coordinates and constant Telemetry Lost Warning. Works fine on TX16S with Crossfire.
Downgrading to 2.2.0 solves the issue. 

### To reproduce
1. Install 2.2.1 on a X9D+ or similar
2. Bind a Crossfire INAV Craft and discover sensors
3. Restart Radio to refresh the LUA Sensor detection
4. Check LUA status

### Expected behavior
LUA Should work normal also with Crossfire

### Screenshots
![image](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/33039058/265fb51a-349a-4824-b7c7-89d4e2546bce)

### Radio and model settings
[opentx-x9d+-eu-lua-noheli-noras-en.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/12342956/opentx-x9d%2B-eu-lua-noheli-noras-en.zip)
[LUA.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/12342961/LUA.zip)
Dart XL (Model Number 4) is the one used here. 

### Additional context
N/A

**Comment by stronnag** [comment]
Please provide a log fiile ..... (or a X9D+ Radio)

**Comment by stronnag** [comment]
Please also provide details of the radio firmware ....

**Comment by b14ckyy** [comment]
> Please also provide details of the radio firmware ....

added LUA, OTX data and Firmware with EEPROM Dump.

**Comment by stronnag** [comment]
Thanks, look forward to seeing the OTX (csv) log.

**Comment by b14ckyy** [comment]
Oh sorry misunderstood you. Here you go.
[iNAV-Wing-2023-08-13.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/12344640/iNAV-Wing-2023-08-13.zip)

**Comment by stronnag** [comment]
Thanks, that looks horribly sane at first glance.

**Comment by b14ckyy** [comment]
Yep, that one works.

**Comment by stronnag** [comment]
It works with ELRS on EdgeTX as well, so we'll go with it.

**Comment by b14ckyy** [comment]
But its interesting that this only seemed to be a problem on the X9D. Worked with no problem on 2.2.1 on the TX16S.

**Comment by b14ckyy** [comment]
Oh good point. I have EdgeTX on mine maybe that's why it worked there.

**Comment by stronnag** [comment]
> Oh good point. I have EdgeTX on mine maybe that's why it worked there.

I expect that is indeed the case ... train wreck
