### ISSUE TITLE
Errore lua script inav

### ISSUE THREAD

**Issue by Alfonsomartina** [iNavFlight/OpenTX-Telemetry-Widget#120]
Salve.. Dopo aver aggiornato edgetx 2.9 su radiomaster tx16s e dopo aver inserito il lua script di inav 2.2.2 sul display il simbolo dei gradi della bussola e del variometro vengono sostituiti da un sibolo che raffigura una chiocciola@. Inoltre accedendo al lua script dininav tramite il pulsante sys si genera un errore syntax. 
![20230913_144213](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/144931338/66fd89a2-4ff2-4601-8ff0-05802a877e6d)
![20230913_133611](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/144931338/9dbf981b-9098-4e94-bf76-0aa4b2e92d59)

**Comment by stronnag** [comment]
https://github.com/iNavFlight/OpenTX-Telemetry-Widget/blob/master/docs/Tips-And-Common-Problems.md#reporting-issues-on-github

**Comment by stronnag** [comment]
> Hi.. After updating edgetx 2.9 on radiomaster tx16s and after inserting the inav 2.2.2 lua script on the display the degrees symbol of the compass and the variometer are replaced by a symbol depicting a snail@. Furthermore, accessing the dininav lua script via the sys button generates a syntax error.

1. The script has not changed, it has always used value 64 (which is indeed `@`). Perhaps the OS has changed the character set. for colour radios. On B&W radios, `°` is displayed correctly.
2. Expected behaviour. This is a telemetry script, you cannot run it from the SYS menu.
