### ISSUE TITLE
Reversed Roll in attitude indicator (artificial horizon) Graphic

### ISSUE THREAD

**Issue by packetkiller** [iNavFlight/OpenTX-Telemetry-Widget#131]
### Describe the bug
The iNAV Telemetry Widget is displaying the attitude indicator graphic roll in reverse (left roll is right roll and right roll is left roll).

TX = RadioMaster TX16S
TX Firmware = 6.17
EdgeTX ver = 2.9.3 "Providence"
RX = TBS Crossfire Diversity Nano
RX Firmware = 6.17
Telemetry Protocol = Crossfire
Flight Controller = MaTekSys H743-WING V3
FC Firmware = iNAV 7.0.1

### To reproduce
1. Turn on all electronics (TX, VRX, Battery connected to aircraft)
2. While looking at the aircraft from the rear (the aircraft pointing away from you in the direction it would normally fly), lower the left wing (simulate a left roll).
3. Look at the iNAV Telemetry Widget on the TX and notice the roll graphic depicts a right roll.
4. Repeat for right roll.
5. Again, look at iNAV Telemetry Widget on the TX and notice the roll graphic depicts a left roll.
Note, all telemetry data indicates good values with the exception of the reversed roll attitude indicator graphic.

### Expected behavior
An aircraft left roll is expected to show a left roll in the iNAV Telemetry Widget. Same for right roll.

### Screenshots
See attached zip for left and right roll with iNAV Telemetry Widget showing reverse roll in attitude indicator graphic.

### Radio and model settings
The model name is OptiAR1.
Note: the other model using the same TX (a quadcopter) displays correctly in the iNAV Widget.
Attached is the .dat and EdgeTX .etx settings backup files.

### Additional context

Also provided is a copy of the iNAV config settings for OptiAR1. Of note may be the orientation of the FC and GPS. (FC trned 90 degrees in aircraft and GPS is turned 180 degrees in aircraft)

[bug_report_2024-02-14_19-17-26.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/14290146/bug_report_2024-02-14_19-17-26.zip)

**Comment by stronnag** [comment]
The widget is an AHI; the behaviour is correct.

**Comment by packetkiller** [comment]
> The widget is an AHI; the behaviour is correct.

What does that mean? So why does the roll display correctly with the quadcopter model but reverse on the flying wing?

**Comment by packetkiller** [comment]
> The widget is an AHI; the behaviour is correct.

Are you saying, after launch, the banking will switch and look like the pilots cockpit view (the way I am expecting it to look)?

**Comment by stronnag** [comment]
The widget reports the data supplied by the radio, it has no knowledge of the platform or the FC configuration.

**Comment by stronnag** [comment]
If you still think there is a problem with the Lua widget, please supply ETX logs and corresponding Blackbox logs that illustrate the alleged bug, with a reference to the timestamp of the data that is not displayed correctly.

**Comment by packetkiller** [comment]
Here is the flight log.

**Comment by packetkiller** [comment]
Here is the TX EdgeTX log.
[TX_LOGS_Opticopter2-2024-04-15-134032.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/14984159/TX_LOGS_Opticopter2-2024-04-15-134032.zip)

**Comment by packetkiller** [comment]
Here is an image of the quad showing orientation of the GPS.  I am holding up same make/model next to the attached one so you see its orientation.
![20240415_130059](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/93966176/1f38f7f9-b0e9-4f67-8e6f-e5e81efd2495)

**Comment by packetkiller** [comment]
Since the upgrade to iNAV 7.1.0, this now is affecting all models.  The logs are from the shown quad but this also affects other fixed wing aircraft. Here is the "diff all" iNAV config file.
[INAV_7.1.0_cli_OPTICOPTER2_diff_20240415_112656.txt](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/14984176/INAV_7.1.0_cli_OPTICOPTER2_diff_20240415_112656.txt)

**Comment by packetkiller** [comment]
The firmware installed on the flight controller is "inav_7.1.0_MATEKH743.hex" and was obtained via the latest stable in the git repo.

**Comment by packetkiller** [comment]
The quad and other models fly as expected.  I am looking for some proof of where the issue lies (FC firmware, iNAV config, EdgeTX config, or iNAV Widget).  The timestamp of the issue is in the logs as it happens all the time and is consistent. Seems to be off 180 degree. As far as I can tell, it looks fine in iNAV and EdgeTX otherwise. Here is video of the issue so you can see what is going on.  Keep in mind, this was working just a version ago with iNAV 7.0.1 on the quad and EdgeTX 2.9 on TX.
[PICT0001a_edit.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/14984369/PICT0001a_edit.zip)

**Comment by packetkiller** [comment]
Since this issue has grown to additional models, I will attempt to obtain logs from the fixed wing I started this issue with. It may take me a few days...

**Comment by sensei-hacker** [comment]
For anyone else who later has the same question, here's what was explained to @packetkiller on Discord:

The title of this issue shows the confusion.  An attitude indicator is not an artificial horizon - they will appear opposite.

![horizon](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/1971284/50051bb9-622e-4330-8f74-159dc76faf24)

![attitude](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/1971284/66de2b38-eca4-4686-a3b9-7042c9af81a9)

**Comment by mmosca** [comment]
Aircraft banking right:

![image](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/23555060/9dc92c50-818f-47e5-bc9d-37b855c7f67c)
