### ISSUE TITLE
Inverted Pitch display on artificial horizon (roll axis is ok)

### ISSUE THREAD

**Issue by akex03** [iNavFlight/OpenTX-Telemetry-Widget#146]
### Describe the bug

On the artificial horizon display, the pitch axis is inverted. 
I'm using a Jumper T16 (edgetx-firmware-v2.9.4), crossfire protocol with Matek ELRS-R24-D,  and flight controller lefei sparrow 2.

### To reproduce

When the FC is moved pitch-up, the artificial horizon displays a pitch-down animation. When the FC is moved pitch-down, the artificial horizon displays a pitch-up animation.

When I go to my telemetry page on my controller, I see that the ptch telemetry is postive when the flight controller is in pitch-up and negative when the flight controller is in pitch-down. @

### Expected behavior

The artificial horizon animation should match the FC movement/position

### Radio and model settings
<!-- Below are the instructions for exporting radio and model settings that are needed to simulate (and hopefully reproduce) your problem:

Please see attached files, I am having issues with model [1.]
[Pitch inverted files.zip](https://github.com/user-attachments/files/15541354/Pitch.inverted.files.zip)

**Comment by MrD-RC** [comment]
Can you please describe what you see on the AHI. When you tilt the nose of the aircraft up. The ground of the AHI should get lower in the display.

**Comment by akex03** [comment]
Hi Darren,When I tilt the nose of the aircraft up, the ground portion of the AHI is getting bigger (blue portion getting smaller) and when I tilt the nose of the aircraft down, the ground portion of the AHI is getting smaller(blue portion getting bigger).Hope this helps,Thanks,Le 4 juin 2024 01 h 06, Darren Lines ***@***.***> a écrit :
Can you please describe what you see on the AHI. When you tilt the nose of the aircraft up. The ground of the AHI should get lower in the display.

**Comment by MrD-RC** [comment]
If you check in INAV Configurator's setup page. Does the on screen model react the same as the real aircraft?

**Comment by akex03** [comment]
Hi Darren,How can I access the Inav configurator's setup page? Is it the one that you place the right stick centered and the left stick up/right? Because in that menu there is only settings.Thanks,Le 4 juin 2024 08 h 03, Darren Lines ***@***.***> a écrit :
If you check in INAV Configurator's setup page. Does the on screen model react the same as the real aircraft?

**Comment by Mysteur-Yo** [comment]
Hi Akex03

you need to connect you model (FC board) to the computer with an USB cable 
then with INav configurator software you can all the parameter of your model and also the movement of the model

the reaction that you describe is look like the FC is mount in your model in reverse position 

![image](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/172062678/9e0e515e-48dc-49f6-a488-29b7f1a218df)

**Comment by akex03** [comment]
Hi,

I'm using a Leifei Sparrow 2 flight controller connected to a crsf/elrs telemetry receiver, the flight controller outputs the following telemetry:  GPS, GSpd, Hdg, Alt, Sats, Rxbt, Curr, Capa, Bat%, Ptch (inverted), Roll, Yaw, FM, 1RSS, 2RSS, RQLY, RSNR, ANT, RFMD, TPWR, TRSS, TQly, TSNR

There is no FC mounting positions configurations. There is only one way to install it.
The telemetry output for pitch is as follows:


  *
When the aircraft nose goes up (pitch-up) the pitch telemetry is positive (units in RAD)
  *
When the aircraft nose goes down (pitch-down) the pitch telemetry is negative (units in RAD)

Is this the normal way?


Thanks,

Alexandre
________________________________
De : Mysteur-Yo ***@***.***>
Envoyé : 7 juin 2024 14:58
À : iNavFlight/OpenTX-Telemetry-Widget ***@***.***>
Cc : akex03 ***@***.***>; Author ***@***.***>
Objet : Re: [iNavFlight/OpenTX-Telemetry-Widget] Inverted Pitch display on artificial horizon (roll axis is ok) (Issue #146)


Hi Akex03

you need to connect you model (FC board) to the computer with an USB cable
then with INav configurator software you can all the parameter of your model and also the movement of the model

the reaction that you describe is look like the FC is mount in your model in reverse position

image.png (view on web)<https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/172062678/9e0e515e-48dc-49f6-a488-29b7f1a218df>

**Comment by MrD-RC** [comment]
The Leifei Sparrow 2 isn't running INAV. This LUA Script is for INAV flight controllers only. We have no control over what data other systems provide.

**Comment by akex03** [comment]
Ok perfect thanks all for your support,Have a nice day,Alexandre Le 11 juin 2024 01 h 20, Darren Lines ***@***.***> a écrit :
The Leifei Sparrow 2 isn't running INAV. This LUA Script is for INAV flight controllers only. We have no control over what data other systems provide.

**Comment by ChenSihao-cee** [comment]
My iNav has the same issue: the data shows correctly in the ground station, and the pitch reading is normal there. But the pitch angle output in the telemetry is reversed compared to what's displayed on the ground station. Any idea how to fix this, mate? Love from China.
