### ISSUE TITLE
Color Issue with the widget under Edge-TX

### ISSUE THREAD

**Issue by Mysteur-Yo** [iNavFlight/OpenTX-Telemetry-Widget#147]
### Describe the bug
the colors of the background and text are the same, that means I can't see the information's of the telemetry 

### Screenshots
with the default colors system of Edge-TX :
![IMG_20240606_092215](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/172062678/278a0421-a45c-43dc-82af-e5873216883a)

with custom colors system :
![IMG_20240606_092358](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/172062678/16a865cd-1db9-4363-a340-b48c3cdd41f3)

If I shut down the model I can see the text in red due to the telemetry lost, that means the text is present in the script 
![IMG_20240606_091758](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/172062678/c514ed05-9d8b-4b8c-91f3-0de7b708c605)

### Radio and model settings
My radio is the Jumper T18 runing wint Edge-TX V2.9.4
![IMG_20240606_092327](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/172062678/3cb51256-7505-4d71-a468-82ac51d2d605)

Thanks.

**Comment by stronnag** [comment]
And your version of the widget?

**Comment by Mysteur-Yo** [comment]
Your question push me to download again and over-right the file widget and script 
now that work very well without color issue

thanks this topic can be close or delete

**Comment by stronnag** [comment]
Indeed, you were using an obsolete, 2 year old version.

**Comment by stronnag** [comment]
The version is shown at satrtup
