### ISSUE TITLE
No Text when connected to RX

### ISSUE THREAD

**Issue by jlt206** [iNavFlight/OpenTX-Telemetry-Widget#149]
Edge-tx16s JB - vers. 2.7.1 - INAV v.7.1.1 - CRSF

When the RX is connected, I loose all the information text and it changes the theme?

![PXL_20240623_111130176](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/4954838/0edf8163-eeb0-492c-b77c-8f732df3122a)
![PXL_20240623_111121573](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/assets/4954838/37c3c085-6b3c-419f-8a75-b86ccfb342ab)

**Comment by stronnag** [comment]
What version of the widget, looks like an ancient, unsupported version.

**Comment by stronnag** [comment]
Please feel free to reopen if you have anything useful to add.

**Comment by onurboyuk07** [comment]
i'm having the same problem myself.is there a solution

**Comment by stronnag** [comment]
> i'm having the same problem myself.is there a solution

Not without a modicum of useful information, in particular the version of the widget you're using.

**Comment by onurboyuk07** [comment]
1.7.2
1.7.5

**Comment by stronnag** [comment]
Unsupported, obsolete, unofficial and known broken versions. 

You should consider upgrading .

**Comment by jlt206** [comment]
So the answer is that this is the wrong version to use and the correct version can be found in the INAV Git Repositry here: https://github.com/iNavFlight/OpenTX-Telemetry-Widget

Like a lot of people I searched for the widget and it bought me here. Seems logical, but here it is no longer supported or updated as far as I can tell.
