### ISSUE TITLE
Release v2.0.0 or v1.7.4 does not include "pic" or "cfg" folders or files

### ISSUE THREAD

**Issue by MRC3742** [iNavFlight/OpenTX-Telemetry-Widget#15]
### Describe the bug
On a new install the SCRIPTS/TELEMETRY/INAV folder does not contain the "pics" folder or the fourteen .png files needed for various icons and backgrounds when using the iNav.lua script.

Also the "cfg" folder is missing from the SCRIPTS/TELEMETRY/INAV folder, which is needed to store configuration files for each model that uses specific configuration selections other than the default settings.
Without this folder the configuration *.dat file is not saved when exiting the configuration screen.

### To reproduce
Remove the SCRIPTS/TELEMETRY/INAV folder and files. 
Reinstall all files from version 2.0.0 release zip file.
Viewing Screen is now missing icons and backround colors.
Also any configuration changes made will reset to defaults when radio is restarted.

Tested on Jumper T16 
EdgeTX current nightly

**Comment by MRC3742** [comment]
Closing this issue as it has been resolved in PR #16
I am now using your linked development v2.0.1

Thanks for the quick update - Rich

**Comment by elyfranco** [comment]
Hi all guys, I would like to install telemetry on my taranis x9D 2019 SE transmitter, assuming I use the flight control of the Inav Matek. Some of you have the experience and time to dedicate to understanding the correct path to follow for installing telemetry on this system of mine. I hope some of you can take this cry for help to heart. Thank you all. Franco
