### ISSUE TITLE
Jumper T15 - Emergency Mode when selecting iNav widget in telemetry setup

### ISSUE THREAD

**Issue by dingrgh** [iNavFlight/OpenTX-Telemetry-Widget#154]
### Description

Jumper T15 (480x320 colour touch screen)
EdgeTX 2.10.2
iNav Lua Telemetry 2.2.4

When setting up the telemetry widget on a new model, selecting the iNav widget immediately causes the TX to crash and go into Emergency Mode.

### To reproduce
On TX, install LuaTelemetry v2.2.4.
In EdgeTX, create a new model.
Select Telemetry and add a new screen (full screen with no tabs or trim displays). Then attempt to select iNav as the widget to be used.
Boom! Emergency mode.
After powering down and up, you are back to a new model with no telemetry screens (other than the default blank one).

This is a new radio so it doesn't appear in the support radio list. If so, then treat this report as a feature request. ;-)

**Comment by stronnag** [comment]
Supported radio  ... didn't think so.

**Comment by stronnag** [comment]
Can you please try latest master and let me know if it fixes the T15 problem? (#155)

**Comment by CCNNCHUN** [comment]
I'm using jumper t15 firmware version edgetx2.10.3
lua 2.2.4 and it still doesn't work
![Screenshot_2024-08-07-00-15-44-663_com tencent mo](https://github.com/user-attachments/assets/8f1a210b-a3af-40de-a735-34a854c08965)

**Comment by stronnag** [comment]
I asked you to test master, not 2.2.4

**Comment by CCNNCHUN** [comment]
> ~我让你测试master，不是2.2.4~
> 
> 抱歉，请测试师傅。它应该由 #155 修复
I tested the master and now it works fine, thanks

**Comment by CCNNCHUN** [comment]
> ~I asked you to test master, not 2.2.4~
> 
> Apologies, please test master. It should be fixed by #155

I tested the master and now it works fine, thanks

**Comment by stronnag** [comment]
Thank you. New release on its way ...
