### ISSUE TITLE
Jumper T15 keeps bringing up menu

### ISSUE THREAD

**Issue by kibbycabbit** [iNavFlight/OpenTX-Telemetry-Widget#157]
### Describe the bug
While viewing iNav widget (either in widget box or full-screen)
- move left stick to top-right corner will bring up menu
- move right stick top or bottom will toggle Min/Max

### Expected behavior
- shouldn't invoke menu nor toggle min/max
- to invoke menu, SYS buttons should be the only button for Jumper T15
- to toggle min/max, turn jog wheel to left or right

### Radio and model settings
- Jumper T15 running on Centurion v2.10.3
- Running iNav LUA v2.2.5 pre-compiled files from: https://github.com/iNavFlight/OpenTX-Telemetry-Widget/releases

**Comment by stronnag** [comment]
The Jumper T15 uses the default behaviour for colour radios
