### ISSUE TITLE
Unable to enter configuration settings on Radiomaster TX12

### ISSUE THREAD

**Issue by macrokernel** [iNavFlight/OpenTX-Telemetry-Widget#17]
### Describe the bug
OpenTX version: 2.3.11
Transmitter model: Radiomaster TX12
Telemetry protocol: FrSky S.Port
RX&TX: QCZEK LRS

I am unable to enter INAV Lua configuration settings on Radiomaster TX12. It is working fine on Frsky Q X7 with the same QCZEK LRS RX&TX. Looks like the problem is that the script is not recognizing TX12 hardware buttons.

### To reproduce
1. Press the TELE button to start the widget
2. Try short and long pressing all buttons and the jog dial to enter configuration
3. Try throttle max, yaw right as suggested for Horus radio
4. No luck

### Expected behavior
Enter the script configuration settings menu by pressing one of the buttons (perhaps PAGE?)

### Additional context
I have checked the docs, but found no answer: https://luatelemetry.readthedocs.io/en/latest/Configuration-Settings/

![image](https://user-images.githubusercontent.com/9429051/136518956-f03c2bb2-0945-4b72-b75d-36d81e03876f.png)

**Comment by stronnag** [comment]
The obvious solution is a long press on the roller. This has the side effect that the **firmware** first pops up the 

| Reset telemetry |
| ---------- |
| Reset flight |

menu which we can't suppress, otoh the user can either dismiss or action this and then gets to the widget menu.

1. Long jog wheel press:
  ![Screenshot-20211009094914-347x177](https://user-images.githubusercontent.com/158229/136651454-d0821938-51eb-42dc-88cb-382e333a8cf4.png)
2. Dismiss with RTN, widget menu:
![Screenshot-20211009094930-316x173](https://user-images.githubusercontent.com/158229/136651469-44d70ab7-6087-492b-ab00-3f52acbeabe9.png)

Unless anyone has any better idea, this is a trivial and obvious fix. It would apply to all non-colour radios with jog wheel (in theory, I'm not going to test them).

**Comment by stronnag** [comment]
Fix has been merged
