### ISSUE TITLE
How to enter the menu? 

### ISSUE THREAD

**Issue by kasatka60** [iNavFlight/OpenTX-Telemetry-Widget#21]
I have a jumper t12 and t-lite (OpenTX 2.3.14). How do I get to the settings menu?

**Comment by stronnag** [comment]
Does [this](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/issues/17) help

**Comment by kasatka60** [comment]
I pressed enter, then return. Does not work.

**Comment by stronnag** [comment]
I'll have a look via the simulator (don't have the radio).

**Comment by kasatka60** [comment]
Maybe I am pushing the wrong way? Doesn't work in the simulator.

**Comment by stronnag** [comment]
> Maybe I am pushing the wrong way? Doesn't work in the simulator.

It won't work in the simulator until we fix it!

**Comment by wx4cb** [comment]
If it is the same as the normal lua, then hold the throttle to the middle
and yaw right until the screen comes up

**Comment by kasatka60** [comment]
Does not work.

**Comment by stronnag** [comment]
The stick commands will only work on the large colour screen radios (Horus and friends (TX16S et al) and NV14.

**Comment by wx4cb** [comment]
sorry, my bad. It’s top right with the left stick

**Comment by julianschweizer** [comment]
This still does not work for my Jumper T-Lite, since "EVT_ROT_LONG" only works for radios with rotary encoder. Jumper T-Lite needs "or event == EVT_DOWN_LONG" (Which is the "Down" key) to enter menu.

Is there a way to  use a virtual key like "EVT_VIRTUAL_***" to support more/most radios? Or can we just add "or event == EVT_DOWN_LONG" for T-Lite support?

**Comment by kasatka60** [comment]
for Jumper T-lite:
[		elseif event == MENU or (not HORUS and  event == EVT_ROT_LONG) then](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/blob/0b9da9888e6fe55f77eedcd983b692b0b858c1f8/src/SCRIPTS/TELEMETRY/iNav.lua#L520)
change:
elseif event == MENU or event == EVT_DOWN_LONG then

**Comment by kasatka60** [comment]
How do I swap the up and down buttons in the menu?

**Comment by stronnag** [comment]
@kasatka60  please try the Zip file in #26 (MDL long for menu).

**Comment by kasatka60** [comment]
syntax error while switching screens (ent batton)
syntax error MDL long for menu

**Comment by stronnag** [comment]
It would much appreciated if **single** issues for a **single** radio were raised per issue, otherwise it makes it very difficult for developers who don't own these radios.

* See https://github.com/iNavFlight/OpenTX-Telemetry-Widget/pull/26#issuecomment-1008316380 . Works in simulators for T12 and T-Lite. 
* As I don't have either radio, there is little more than can be done without more detail by enabling debug lua mode.

**Comment by kasatka60** [comment]
jumper t12 pro opentx 2.3.14
Syntax error inav.lua:494 attempt to call a nil value

**Comment by kasatka60** [comment]
I started this archive in the simulator and after that it worked. Only the up and down buttons in the menu are confused 
jumper t12 pro opentx 2.3.14

**Comment by stronnag** [comment]
So let see if I understand this:

* On the T12 device you get the `Syntax error inav.lua:494 attempt to call a nil value` error (OTX 2.3.14)
* In the simulator (OTX 2.3.14), it works. Excellent.

I guess there could be some old file on the device that is not overwritten. Can you please try the following:
* remove  the `WIDGETS/iNav` directory
* remove the `SCRIPTS/TELEMETRY/iNav` directory
* remove the `SCRIPTS/TELEMETRY/iNav.lua` file
* Reinstall the inav widget from the Zip file
* Power cycle the device

On the matter of the keys,the script uses `EVT_VIRTUAL_INC` (Next) and `EVT_VIRTUAL_DEC`  (Previous) for navigation in uniformly across all radios. The mapping is  defined by OpenTX `radio/src/lua/api_general.cpp`,  e.g.
```
 { "EVT_VIRTUAL_DEC", EVT_KEY_FIRST(KEY_DOWN) },
 { "EVT_VIRTUAL_INC", EVT_KEY_FIRST(KEY_UP) },
```
If you feel this wrong for the T12, please raise an issue with OpenTX.

**Comment by kasatka60** [comment]
I formatted the SD. Syntax error
After the simulator, the script works fine on the device. Except the up and down buttons.
Maybe I have a bad firmware.

**Comment by stronnag** [comment]
I don't know, however:
* The key mapping is defined by OpenTX, not us
* The inav widget works on the simulator, that is all I can test

So I'll close this issue and merge #26 later today, which is the best I can do for t-lite and t-12.

**Comment by stronnag** [comment]
Here's the final last shot. Please try the Zip below (on the radio). The only difference is that is it compiled on the desktop rather than on the device. It's often the case that in the simulator only "on-device" compiled lua will work; maybe the opposite applies to the radio?
[LuaTelemetry_v2.0.2-rc2.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/7839653/LuaTelemetry_v2.0.2-rc2.zip)

**Comment by kasatka60** [comment]
Everything worked on the jumper t12 pro. As for the up and down buttons, I will figure it out myself. Everything worked correctly on older versions.

**Comment by stronnag** [comment]
Excellent. We have changed nothing in regard to the buttons (as far as I'm aware).

**Comment by kasatka60** [comment]
Jumper t-lite opentx 2.3.14 
Everything worked correctly. Only the up and down buttons in the menu are confused

**Comment by 2090570729** [comment]
Is it possible to set the required remote control interface on the computer to import the device?

**Comment by 2090570729** [comment]
此屏幕能否设置为默认打开

![image](https://user-images.githubusercontent.com/103346720/162610117-92535d26-4310-4232-889d-956f95c4a139.png)

**Comment by 2090570729** [comment]
Can this screen be set to open by default

![image](https://user-images.githubusercontent.com/103346720/162610211-93d83818-6b3e-4ea4-b22c-c66fa8369cd5.png)

**Comment by kasatka60** [comment]
Veiw mode: Pilot

**Comment by kasatka60** [comment]
> Is it possible to set the required remote control interface on the computer to import the device?

Try to set it up in opentx/egdetx simulator.

**Comment by 2090570729** [comment]
In fact, the problem has been solved, and the interface can be switched normally? Thank you blogger,

**Comment by 2090570729** [comment]
In fact, the problem has been solved, the interface can be switched normally, thank you blogger,

**Comment by kasatka60** [comment]
Do you mean "normally switch"?

**Comment by 2090570729** [comment]
Yes, it can be switched normally. I am using openTX2.3.14

**Comment by 2090570729** [comment]
Uploading video_20220415_230134.mp4…

**Comment by 2090570729** [comment]
Uploading video_20220415_231226_edit.mp4…

**Comment by 2090570729** [comment]
Uploading video.mp4…

**Comment by 2090570729** [comment]
I don't know, can you watch it?

**Comment by nm17** [comment]
@2090570729 No, I can only see the text
