### ISSUE TITLE
No voltage visible when using Betaflight with ImmersionRC Ghost telemetry.

### ISSUE THREAD

**Issue by sylphio** [iNavFlight/OpenTX-Telemetry-Widget#38]
Tx16s on edgeTx 2.6 with Ghost module (race mode with telemetry).
Drone on betaflight 4.3-rc3 
OpenTX-Telemetry-Widget on dev latest.

![20220227_014042](https://user-images.githubusercontent.com/1335813/155871496-44549b6a-44a9-432e-b45a-bea362a7d346.jpg)

The INAV widget do not display the battery information properly. 
The telemetry is working as the up-right corner display the correct voltage.

Thank you

**Comment by stronnag** [comment]
This is the **INAV** widget. The documentation lists several INAV requirements for the battery-power widget to display data. 
Please check that Betaflight means these requirements. If you can show that βF does meet the requirement  (i.e. relevent fragment of CLI `diff`), then please  reopen the issue with a TX telemetry log attachment so we can investigate further.

**Comment by stronnag** [comment]
And for completeness, for (non-CRSF) the value in the right title bar is `RxBt` and the value used in the voltage / battery status widget is `VFAS` , as this is the Smartport convention.
