### ISSUE TITLE
When I connected, got error(Script syntax error bad argument #1 to 'getV')

### ISSUE THREAD

**Issue by Addison666** [iNavFlight/OpenTX-Telemetry-Widget#49]

**Comment by stronnag** [comment]
Care to provide some more information:
* Which OS and version (Edge, OpenTX etc.)
* Which TX model.

**Comment by Addison666** [comment]
Open TX, MAMBO
version：TBS-1.3.0
Receiver：Tracer RX

**Comment by stronnag** [comment]
versions of OpenTX are typically 2.3.15 etc. Is this an official OpenTX build?

**Comment by Addison666** [comment]
> 

I think no official, maybe FW: fdtx-mambo

**Comment by stronnag** [comment]
Please take the matter up with TBS "support" then; they can have our code, we don't have theirs.

* Not supported hardware
* Not supported firmware

**Comment by Addison666** [comment]
> Please take the matter up with TBS "support" then; they can have our code, we don't have theirs.
> 
> * Not supported hardware
> * Not supported firmware

I checked version refer to official 1.2v0026

**Comment by stronnag** [comment]
Which does not exist. Typical TBS, the Boris Johnson of support "obfuscate, deny, blame anyone else, deny, obfuscate...".
Please also check the list of supported OTX versions and hardware on our github page.

**Comment by Addison666** [comment]
> 

The issue were happened when I had connected the receiver.
I import the script work well.

**Comment by stronnag** [comment]
Still unsupported ...
