### ISSUE TITLE
How to activate the flight mode change item

### ISSUE THREAD

**Issue by Ettore67** [iNavFlight/OpenTX-Telemetry-Widget#52]
Hi Guys I need a support, I have installed the latest version of Inav lua on my Taranis X9D SE 2019 transmitter. Everything seems to work fine, I ask why when I change flight mode from Acro to Manual no voice reminds me that I have switched from a mode to the other, how can I enable this function that I find convenient? Thanks in advance for your contribution.
Franco

### To reproduce

1. Go to '....'
4. Should it be doing this?

**Comment by stronnag** [comment]
You can implement this in OTX / ETX.
