### ISSUE TITLE
[Feature Request].  Support Betafpv literadio 3 pro.

### ISSUE THREAD

**Issue by sikolenski** [iNavFlight/OpenTX-Telemetry-Widget#53]
### Describe the bug
the script works well, but there's no way to go in configuration menu. It seem like there'is no assigned button to do that.

**Comment by stronnag** [comment]
Not a supported radio.

It is supported in the Edge Companion?

**Comment by stronnag** [comment]
Once the radio is supported by a EdgeTx release (including in Companion), then we can considering supporting it. Please note that none of the developers have this radio and without Companion support, we cannot proceed.

**Comment by sikolenski** [comment]
ok, thx for your answer

**Comment by stronnag** [comment]
This should be working in the `lr3pro` branch with EdgeTX 2.8 lastest (probably also -rc4).
You can enter the menu by a **long press** on the right 'button':
![lr3pro](https://user-images.githubusercontent.com/158229/204083355-25e92aa8-b1a7-497e-b7a4-8280d70d49d7.png)

@sikolenski , can you please try this archive **on the radio**?
[LuaTelemetry_v2.2.0-lr3.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/10096030/LuaTelemetry_v2.2.0-lr3.zip)

**Comment by stronnag** [comment]
closing as fix is merged without any feedback from the OP
