### ISSUE TITLE
[Feature request] Larger Battery Capacity

### ISSUE THREAD

**Issue by Muirson** [iNavFlight/OpenTX-Telemetry-Widget#55]
Hi, 

Can we please have a larger battery capacity option such as 20000mah?

**Comment by stronnag** [comment]
Don't see why not ... in progress.

**Comment by stronnag** [comment]
Care to give this a try?

[LuaTelemetry_v2.1.1-rc3.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/9432852/LuaTelemetry_v2.1.1-rc3.zip)

**Comment by Muirson** [comment]
Just tested it, Seems to work quite well. I have the capacity i wanted plus the future one ill need.. Thanks
