### ISSUE TITLE
Detect Crossfire - better solution

### ISSUE THREAD

**Issue by TomekFrs** [iNavFlight/OpenTX-Telemetry-Widget#57]
When Mavlink protocol is used between Ardupilot and Crossfire TX, 'FM' (flight mode) don't show in sensors.
For this reason script doesn't detect CRSF and not work properly.

Solution: 
change in 'other.lua' FM -> RFMD (RFMD - uplink, update rate - is always in sensors when used Crossfire TX)

data.fm_id = getTelemetryId("RFMD") > -1 and getTelemetryId("RFMD") or getTelemetryId("PV")

**Comment by stronnag** [comment]
Ignoring that this project is not targeted at either Ardupilot or MAVLink ... in none of my (albeit small) collection of CRSF examples does the 'PV' key occur.

We can add this test **in addition** to 'FM' test (which is always present for the target INAV audience).
The test only runs at startup so the overhead is minimal.
