### ISSUE TITLE
CRSF Transmitter Power not working

### ISSUE THREAD

**Issue by skaman82** [iNavFlight/OpenTX-Telemetry-Widget#59]
### Describe the bug
On CRSF the transmit power indicator stopped working. 
I am on CRFS FW 6.17 and OpenTX 2.3.15 on my TX16s

### To reproduce
- Create new model
- Discover Telemetry sensors
- Run the Telemetry Widget

### Expected behavior
Usually the widget is showing the transmit power of the CRSF module. 
I have another, older model on my radio (didn't refreshed sensor discovery on that) - there the mw Value is showing up normally - same FW and hardware.

### Screenshots
old model - no new sensor discovery
![screen-2022-09-15-125429](https://user-images.githubusercontent.com/11768024/190378324-70c6f3c6-e0be-4bde-8d9e-58987c0503bd.jpg)

new model - with new sensor discovery. I also noted the name TPW2 is different - on the old model it is TPWR.
![screen-2022-09-15-125518](https://user-images.githubusercontent.com/11768024/190378453-b7f5da94-f119-4a4f-85d9-f0903cd5d406.jpg)
![screen-2022-09-15-125542](https://user-images.githubusercontent.com/11768024/190378460-06835e78-4b05-4dbb-bc86-b7eaeda3e204.jpg)

**Comment by skaman82** [comment]
Renaming the sensor manually into "TPWR" instead "TPW2" solves the issue

**Comment by stronnag** [comment]
As this can be fixed by configuration rather than another exception in the code, I'm minded to close this.
