### ISSUE TITLE
Battery level display error

### ISSUE THREAD

**Issue by PULLUUUUUUUUUUP** [iNavFlight/OpenTX-Telemetry-Widget#63]
hello to all devs
Describe the bug
Battery level display error  on my TBS MAMBO and X9D 2019 (OpenTX 2.3.14)

Whether the problem is the flight controller?

To reproduce
The radio power on before the drone
Running the script
Percentage of battery is 0%
Battery voltage error

When The radio power on after the drone.The problem will be solved

Screenshots

**Comment by stronnag** [comment]
* Not a supported radio
* Not supported firmware if it's the TBS fork 

* Works fine on supported radios / firmware
* Please contact TBS for support

**Comment by PULLUUUUUUUUUUP** [comment]
The problem also occurred on X9D + 2019

**Comment by stronnag** [comment]
* It does not happen on the maintainer's hardware. Thus it cannot be investigated further
* The script depends on the radio providing the available sensors. If the radio (reasonably) cannot do that if the model is not powered, then the script cannot show that data.
* Invoking the script and expecting it to work prior to powering the model is undefined behaviour.
