### ISSUE TITLE
iNav Telemetry on iFlight commando8

### ISSUE THREAD

**Issue by Cloudfan-official** [iNavFlight/OpenTX-Telemetry-Widget#66]
To Developers:
I want to run Telemetry Lua on iFlight commando8（EdgeTX 2.8.0）

But I can't enter the "Configuration menu", even if I press the "menu" button on the remote control.
Other operations are OK.

How can I solve this problem？
Thanks.

**Comment by stronnag** [comment]
Please provide a link to the user guide. As the radio is supported by EdgeTX companion, it may be possible to enable the menu.

**Comment by Cloudfan-official** [comment]
EdgeTX said that it support iFlight commando8 in v2.8.0:
https://github.com/EdgeTX/edgetx/releases/tag/v2.8.0

What is your mean? user manual? or other things?
I've just started using "EdgeTX", and I still don't know something.

**Comment by stronnag** [comment]
The user manual ...

**Comment by Cloudfan-official** [comment]
![00001](https://user-images.githubusercontent.com/93080288/209316367-2b808831-2dec-4cc7-a39a-f27c302d828e.jpg)
![00002](https://user-images.githubusercontent.com/93080288/209316374-20a926cd-5f5f-485a-af09-4e9c054c9eb5.jpg)
![00003](https://user-images.githubusercontent.com/93080288/209316378-f15fe730-2a77-4700-a449-e3213b1431e9.jpg)
![00004](https://user-images.githubusercontent.com/93080288/209316382-0061bbb5-8121-4c26-bb26-bf57ab629842.jpg)
![00005](https://user-images.githubusercontent.com/93080288/209316385-69f2f798-b5f2-49fc-a070-450b97fda5a7.jpg)
![00006](https://user-images.githubusercontent.com/93080288/209316388-1f3e83e9-5608-4b98-b48c-dd01e1b23a6d.jpg)
They only gave such a simple user manual.

**Comment by stronnag** [comment]
In that case it's not possible without the radio. Even then, with only two buttons, it may not be possible. 

Please contact the vendor for support.
