### ISSUE TITLE
Lua Telemetry can't work on Flysky EL18

### ISSUE THREAD

**Issue by Taical** [iNavFlight/OpenTX-Telemetry-Widget#74]
### Describe the bug

I have a Flysky EL18 using Crossfire, can't get Lua Telemetry work on it
### To reproduce

1. Go to 'Screen Settings'
2. Layout 'Full screen'
3. Click on 'Setup widgets'
4. Select widget choose 'iNav'
5. See 'ERROR in refresh(): bad argument # 1 to 'getValue' (string expected, git nil'

### Expected behavior

Get a view of INAV Lua Telemetry

**Comment by stronnag** [comment]
**This is not a supported device.**
The active maintainer does not own such a device.
It may be possible to enable support via the simulator in the future.
