### ISSUE TITLE
Compatibility with ELRS @ 50 Hz 

### ISSUE THREAD

**Issue by jlpoltrack** [iNavFlight/OpenTX-Telemetry-Widget#81]
### Is your feature request related to a problem? Please describe
The widget doesn't seem to like ELRS 2.4 @ 50 Hz (even with 1:2 TLM).  The widget will only load a few values and in general not work as expected.  Switching to 100 Hz full addresses the problem.  Have tried lowering the TLM_REPORT_INTERVAL_MS to 10 ms without success.

### Describe the solution you'd like
The widget to work as expected with 50 Hz mode.

### Describe alternatives you've considered
Have tried choosing the highest telemetry rate (1:2) which should provide enough data.  For example, if I choose 100 Hz full with 1:32 ratio, this is much less data but the widget seems to work as expected.
### Additional context

N/A

**Comment by stronnag** [comment]
The widget works on data that OpenTX / EdgeTX provides, so this is most likely not a widget issue.
If you wish to have this issue reopened, please provide the full [information described in the documentation](https://luatelemetry.readthedocs.io/en/latest/Tips-And-Common-Problems/) "Reporting Issues on Github".
